### ISSUE TITLE
Slow Build

### ISSUE THREAD

**Issue by A-Kamaee** [AngularShowcase/ng2-bootstrap-sbadmin#6]
Hi, Whenever I change little thing gulp watch detect change and build start, last time it took about 3 min.

PS: I'm really new in gulp, so feel free to give me any suggestion. :)

**Comment by ludohenin** [comment]
This repo hasn't been updated for a while, you might be better of starting from the latest master of [angular2-seed](https://github.com/mgechev/angular2-seed)

**Comment by A-Kamaee** [comment]
ok thanks.
